#!/usr/bin/env python
# -*- coding: utf-8 -*-

'''
Output a json files containing all the ice cream in the freezer.
'''

from __future__ import print_function

from json import loads, dumps
from os import environ
from sys import exit, stderr

from redis import StrictRedis

try:
    REDIS_HOST = environ['REDIS_HOST']
    REDIS_PORT = environ['REDIS_PORT']
except KeyError:
    print('Please set the environment variables:',
          'REDIS_HOST', 'REDIS_PORT',
          file=stderr)
    exit(1)

redis_client = StrictRedis(host=REDIS_HOST, port=REDIS_PORT)

icecream_ids = redis_client.keys('icecream_*')
icecreams = redis_client.mget(icecream_ids)

data = {'icecreams': []}
data['icecreams'] = [loads(icecream) for icecream in icecreams]

print(dumps(data))
